version: 2

registries:
  github-npm:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.GITHUB_TOKEN}}

updates:
  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - github-npm
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/sdk"
    registries:
      - github-npm
    schedule:
      interval: "weekly"
