name: SIP SDK Release

on:
  push:
    tags:
      - "sip-sdk-v*"

permissions:
  contents: read
  packages: write

jobs:
  publish:
    name: Publish SIP SDK
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com

      - name: Install
        run: npm ci

      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
