name: SIP SDK Release

on:
  push:
    tags:
      - "sip-sdk-v*"
  workflow_dispatch:

permissions:
  packages: read
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 26
          registry-url: https://npm.pkg.github.com
          scope: "@alialkhtri3-png"

      - name: Install SDK dependencies
        run: |
          cd sdk
      - name: Configure GitHub Packages auth
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Install SDK dependencies
        run: |
          cd sdk
          npm install

      - name: Publish SIP SDK
        run: |
          cd sdk
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
